name: Vinayakar Chathurthi

on:
  push:
    branches: ["nalinture-patch-1"]

jobs:
  - name: Pillaiyar
    runs-on: self-hosted

    steps:
      - name: Birthday Wishes
        run: echo "Happy Birthday Pillaiyarappa"
